name: "Pull Directory Action"
description: "Pull directory from a repository and push to the current repository"
inputs:
  source-repo:
    description: "Source repository to pull directory"
    required: true
  source-folder-path:
    description: "Source repository path folder to be pulled"
    source: true
  source-branch:
    description: "Source repository branch to pull the directory"
    required: true
    default: "main"
  target-branch:
    description: "Target repository branch to push the directory"
    required: true
    default: "main"
  git-username:
    description: "Username to be used by git"
    required: true
    default: "github-actions"
  git-email:
    description: "Email to be used by git"
    required: true
    default: "github-actions@github.com"
runs:
  using: "composite"
  steps:
    - run: |
        sh ${{ github.action_path }}/action.sh \
          ${{ inputs.source-repo }} \
          ${{ inputs.source-folder-path }} \
          ${{ inputs.source-branch }} \
          ${{ inputs.target-branch }} \
          ${{ inputs.git-username }} \
          ${{ inputs.git-email }}
      shell: bash
