name: 'Pull Directory Action'
description: 'Pull directory from another repository and push to the current repository'
inputs:
  destination-repo:
    description: 'Target repository to pull directory'
    required: true
  destination-folder-path:
    description: 'Target repository path folder to be pulled'
    required: true
  destination-branch:
    description: 'Target repository branch to pull the directory'
    required: true
    default: 'main'
  source-branch:
    description: 'Source repository branch to push the directory'
    required: true
    default: 'main'
  git-username:
    description: 'Username to be used by git'
    required: true
    default: 'github-actions'
  git-email:
    description: 'Email to be used by git'
    required: true
    default: 'github-actions@github.com'
runs:
  using: "composite"
  steps:
    - run: |
        sh ${{ github.action_path }}/action.sh \
          ${{ inputs.destination-repo }} \
          ${{ inputs.destination-folder-path }} \
          ${{ inputs.destination-branch }} \
          ${{ inputs.source-branch }} \
          ${{ inputs.git-username }} \
          ${{ inputs.git-email }}
      shell: bash
